### ISSUE TITLE
Fix Dark compilation on openJDK 14

### ISSUE THREAD

**Issue by mf-code** [jdi-testing/jdi-dark#450]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jdi-dark: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jdi-dark: Fatal error compiling

**Comment by romaha08** [comment]
After my research I found that problem is with maven-dependency-plugin
```
<groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
```
**Erorr happens on step** 
 --- maven-dependency-plugin:3.1.2:copy (copy-rest-service) @ jdi-dark-tests ---
[INFO] Configured Artifact: com.epam.jdi:jdi-dark-rest-service:1.0.0:jar
[INFO] Copying classes to D:\GIT\jdi-dark\jdi-dark\jdi-dark-tests\target\rest-service\jdi-dark-rest-service.jar

**Exception is:**
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:copy (copy-rest-service) on project jdi-dark-tests: Artifact has not been packaged yet. When used on reactor artifact, copy should
be executed after packaging: see MDEP-187.

**So here is a bug in open step:**
https://issues.apache.org/jira/browse/MDEP-187

As a resolution - we can't fix this issue.

**Comment by pnatashap** [comment]
The reason for the issue was java.xml.soap package which was removed from JDK11.
Package is changed to jakarta.xml.soap, as a result compilation works fine for now.

Additional info: root cause error is visible only with parameter <forceJavacCompilerUse>true</forceJavacCompilerUse> for maven-compiler-plugin
